"""referee contacts as non-user roster, redo assignments and evaluations

Revision ID: 67ac6cc2dc90
Revises: 9475f710221b
Create Date: 2026-08-01 12:45:32.027626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ac6cc2dc90'
down_revision: Union[str, None] = '9475f710221b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('qualification_badge', sa.Enum('YOUTH_LOCAL', 'SEMI_PRO', 'TOP_TIER_NATIONAL', 'CAF', 'FIFA', name='qualificationbadge'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('match_assignments', sa.Column('referee_contact_id', sa.String(), nullable=False))
    op.drop_constraint('match_assignments_assigned_by_id_fkey', 'match_assignments', type_='foreignkey')
    op.drop_constraint('match_assignments_referee_id_fkey', 'match_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'match_assignments', 'referee_contacts', ['referee_contact_id'], ['id'])
    op.drop_column('match_assignments', 'referee_id')
    op.add_column('referee_evaluations', sa.Column('referee_contact_id', sa.String(), nullable=False))
    op.drop_constraint('referee_evaluations_referee_id_fkey', 'referee_evaluations', type_='foreignkey')
    op.drop_constraint('referee_evaluations_evaluated_by_id_fkey', 'referee_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'referee_evaluations', 'referee_contacts', ['referee_contact_id'], ['id'])
    op.drop_column('referee_evaluations', 'referee_id')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('qualification_badge', sa.Enum('YOUTH_LOCAL', 'SEMI_PRO', 'TOP_TIER_NATIONAL', 'CAF', 'FIFA', name='qualificationbadge'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qualification_badge')
    op.drop_column('users', 'phone_number')
    op.add_column('referee_evaluations', sa.Column('referee_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referee_evaluations', type_='foreignkey')
    op.create_foreign_key('referee_evaluations_evaluated_by_id_fkey', 'referee_evaluations', 'users', ['evaluated_by_id'], ['id'])
    op.create_foreign_key('referee_evaluations_referee_id_fkey', 'referee_evaluations', 'users', ['referee_id'], ['id'])
    op.drop_column('referee_evaluations', 'referee_contact_id')
    op.add_column('match_assignments', sa.Column('referee_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match_assignments', type_='foreignkey')
    op.create_foreign_key('match_assignments_referee_id_fkey', 'match_assignments', 'users', ['referee_id'], ['id'])
    op.create_foreign_key('match_assignments_assigned_by_id_fkey', 'match_assignments', 'users', ['assigned_by_id'], ['id'])
    op.drop_column('match_assignments', 'referee_contact_id')
    op.drop_table('referee_contacts')
    # ### end Alembic commands ###
