"""add referee department head flag and referee module tables

Revision ID: 9475f710221b
Revises: 6f772f0b056e
Create Date: 2026-07-31 15:05:24.789122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9475f710221b'
down_revision: Union[str, None] = '6f772f0b056e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('match_title', sa.String(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('referee_id', sa.String(), nullable=False),
    sa.Column('assigned_by_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'CONFIRMED', 'DECLINED', name='assignmentstatus'), nullable=False),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referee_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('referee_id', sa.String(), nullable=False),
    sa.Column('evaluated_by_id', sa.String(), nullable=False),
    sa.Column('fitness_score', sa.Float(), nullable=False),
    sa.Column('decision_making_score', sa.Float(), nullable=False),
    sa.Column('game_management_score', sa.Float(), nullable=False),
    sa.Column('positioning_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['match_assignments.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('is_department_head', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_department_head')
    op.drop_table('referee_evaluations')
    op.drop_table('match_assignments')
    # ### end Alembic commands ###
